# Generated by Django 5.0.6 on 2024-06-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0043_auto_20220428_1310"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(default="menu/image.jpeg", upload_to="menu/"),
        ),
    ]
