# Generated by Django 5.0.6 on 2024-06-02 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0046_rename_out_date_ingredient_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
