# Generated by Django 5.0.6 on 2024-06-02 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0047_alter_ingredient_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="status_date",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="provider",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.provider",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
