# Generated by Django 5.0.6 on 2024-06-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0048_ingredient_status_date_alter_ingredient_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("KILO", "KILO"),
                    ("LITRE", "LITRE"),
                    ("GRAM", "GRAM"),
                    ("MILLILITRE", "MILLILITRE"),
                    ("UNIT", "UNIT"),
                    ("OTHER", "OTHER"),
                ],
                max_length=10,
            ),
        ),
    ]
