# Generated by Django 5.0.6 on 2024-06-03 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0050_ing_category_ingredient_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="category",
            field=models.ForeignKey(
                blank=True,
                max_length=10,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.ing_category",
            ),
        ),
    ]
